services:
  cron-runner:
    build: cron-runner
    container_name: fogcast-cron-runner
    restart: always
    volumes:
      - type: bind
        source: ./csv-data
        target: /app/csv-data
      - type: bind
        source: ./cron-logs
        target: /app/logs
    networks:
      - proxy-net

  status-reporter:
    build: cron-status
    container_name: fogcast-status-reporter
    restart: always
    depends_on:
      - cron-runner
    volumes:
      - type: bind
        source: ./cron-logs
        target: /app/logs
    environment:
      - LOG_PATH=/app/logs/cron.log
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://fogcast-status-reporter:8000/health-check || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
